version: "3.8"

services:
  InventorySystemApi:
    image: dechertnicholas/inventorysystemapi:latest
    container_name: InventorySystemApi
    depends_on:
      - db
    ports:
      - 8090:8090/tcp
    environment:
      - DATA_SOURCE=jdbc:postgresql://db:5432/inventorysystemapi
      - ISAPI_USERNAME=postgres
      - ISAPI_PASSWORD=toor

  db:
    image: postgres:latest
    container_name: InventorySystemApi_Database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=toor
      - POSTGRES_DB=inventorysystemapi
